name: json_serializable_common_converters
description: A package to provide common converters for json_serializable.
version: 1.0.0

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.0.0

dependencies:
  json_annotation: ^4.9.0
